name: Compilar KernelSU Moto G42
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar Codigo
      uses: actions/checkout@v4

    - name: Configurar Ferramentas do Sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libssl-dev libcrypto++-dev bison flex libelf-dev lld llvm clang
        
    - name: Injetar KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: Compilar Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Usamos o Clang nativo da máquina com o linkador moderno LLD
        make vendor/hawao_defconfig
        make CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

    - name: Guardar Kernel Pronto
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_MotoG42_KSU
        path: arch/arm64/boot/Image
