name: Compilar KernelSU Moto G42
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Baixar Codigo
      uses: actions/checkout@v4

    - name: Injetar KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: Compilar Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Ignora checagens chatas de versão do script da LineageOS
        export KBUILD_BUILD_HOST=github-actions
        export KBUILD_BUILD_USER=builder
        
        # Gera a configuração e compila usando o Clang nativo que JÁ ESTÁ pronto no GitHub
        make vendor/hawao_defconfig
        make CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- -j$(nproc)

    - name: Guardar Kernel Pronto
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_MotoG42_KSU
        path: arch/arm64/boot/Image
