name: Compilar KernelSU Moto G42
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Baixar Codigo
      uses: actions/checkout@v4

    - name: Injetar KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: Compilar Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Cria arquivos de checagem para o script da LineageOS não reclamar do compilador nativo
        mkdir -p bin
        ln -sf /usr/bin/clang bin/clang
        ln -sf /usr/bin/ld.lld bin/ld.lld
        export PATH=$(pwd)/bin:$PATH
        
        # Força a configuração da árvore do Moto G42
        make hawao_defconfig || make vendor/hawao_defconfig || make vendor/bengal_defconfig || make bengal_defconfig
        
        # Compila com as ferramentas nativas que já estão na máquina
        make CC=clang LD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

    - name: Guardar Kernel Pronto
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_MotoG42_KSU
        path: arch/arm64/boot/Image
